 
version: "3"

services:
  redis:
    image: redis:latest
    container_name: line-bot-service-redis
    ports:
      - 9000:6379
    expose:
      - 6379
      
  database:
    image: postgres:11.1
    container_name: line-bot-service-pg
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=db
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    ports:
      - "10000:5432"
    expose:
      - "5432"

  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    # image: oring/taoyuan-streetlight-line-bot-service:latest
    container_name: line-bot-service-app
    environment:
      - PG_HOST=database
      - PG_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - database
      - redis
    volumes:
      - ./src:/app/src
    ports:
      - 8108:8108 #app

# volumes:
#   db-data:
#     driver: local